### ISSUE TITLE
`npm install` needs to be run twice to get webpack-dev-server to work 

### ISSUE THREAD

**Issue by igor-ka** [rangle/ng-typescript-webpack-starter#1]
After cloning the repo clean, or removing the node_modules folder, `npm install` needs to be run a second time in order to get webpack-dev-server to start. Otherwise, there is an error when calling either `npm start` or `webpack-dev-server` command.

Both webpack and webpack-dev-server are specified as devDepenencies in package.json

**Comment by kosz** [comment]
1) should the new `npm start` also run the build script before it starts the server ? 
2) do we want to default to http-server here or should this seed also include some pm2 setup of sorts ?

**Comment by kosz** [comment]
Cannot reproduce in my PR. `postinstall` now runs `npm run build` so that may have fixed it

**Comment by igor-ka** [comment]
@kosz awesome news lets close it then

**Comment by kosz** [comment]
testing on master now Igor. Will take action if I can reproduce on master.

**Comment by kosz** [comment]
@igor-ka can't reproduce on master ¯\_(ツ)_/¯

**Comment by kosz** [comment]
can't reproduce
