### ISSUE TITLE
Add production build support

### ISSUE THREAD

**Issue by igor-ka** [rangle/ng-typescript-webpack-starter#4]
We need to add production build support for things that are only require for production, i.e. add UglifyJsPlugin to minify and mangle code, which slows down the re-build command during development.

**Comment by kosz** [comment]
what should this production be based on ? a special npm script ? a special flag ? an environment variable ?

**Comment by igor-ka** [comment]
As we discussed npm script here mean to run a basic node + express server to serve the application. Environmental variable can be defined by using DefinePlugin as well as using it while defining different script in package.json
